<?php

namespace Kafe\ArmureManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrasRepository extends EntityRepository
{
}
