<?php

namespace Kafe\ArmureManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BustierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BustierRepository extends EntityRepository
{
}
